// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-4Wg8TIsTeWHzttcxQniNWCchSAHy74U',
    appId: '1:518698127442:android:67a13d5b1f022c64144f8b',
    messagingSenderId: '518698127442',
    projectId: 'districtfood-e0f9b',
    storageBucket: 'districtfood-e0f9b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB44pY9N0nAdXrpcFlQBYWOwlS0ykq_eKw',
    appId: '1:518698127442:ios:82064ed85000cee3144f8b',
    messagingSenderId: '518698127442',
    projectId: 'districtfood-e0f9b',
    storageBucket: 'districtfood-e0f9b.firebasestorage.app',
    androidClientId: '518698127442-0g68thtfj0s6te77c7jugnvspim0uumv.apps.googleusercontent.com',
    iosClientId: '518698127442-nsihmg2f3qpa32eoohmch107212l492i.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeawayApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwG04UCHjgQEWXYH15CoQ8Jn9dbYuIkwA',
    appId: '1:518698127442:web:5be936db727df5d7144f8b',
    messagingSenderId: '518698127442',
    projectId: 'districtfood-e0f9b',
    authDomain: 'districtfood-e0f9b.firebaseapp.com',
    storageBucket: 'districtfood-e0f9b.firebasestorage.app',
    measurementId: 'G-ZESEY1LRS9',
  );
}
