import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'firebase_options.dart'; // generated by flutterfire configure (placeholder here)
import 'providers/cart_provider.dart';
import 'providers/auth_provider.dart';
import 'screens/splash_screen.dart';
import 'screens/sign_in_screen.dart';
import 'screens/sign_up_screen.dart';
import 'screens/forgot_password_screen.dart';
import 'screens/email_verification_screen.dart';
import 'screens/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => CartProvider()),
        ChangeNotifierProvider(create: (_) => AppAuthProvider()),
      ],
      child: Consumer<AppAuthProvider>(builder: (context, auth, _) {
        return MaterialApp(
          title: 'Takeaway',
          theme: ThemeData(
            useMaterial3: true,
            colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepOrange),
          ),
          // AuthGate decides whether to show home or signin based on auth state.
          home: AuthGate(),
          routes: {
            '/signin': (_) => SignInScreen(),
            '/signup': (_) => SignUpScreen(),
            '/forgot-password': (_) => ForgotPasswordScreen(),
            '/email-verification': (_) => EmailVerificationScreen(),
            '/home': (_) => HomeScreen(),
          },
        );
      }),
    );
  }
}

class AuthGate extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final auth = Provider.of<AppAuthProvider>(context, listen: false);
    return StreamBuilder<User?>(
      stream: auth.authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) return SplashScreen();
        if (snapshot.hasData) return HomeScreen();
        return SignInScreen();
      },
    );
  }
}
